export const SKILL_ACTIONS_DATA = [
  {
    key: 'Disarm',
    label: 'PF2E.Actions.Disarm.Title',
    proficiencyKey: 'ath',
    trainingRequired: true,
    icon: 'perfect-strike',
    featRequired: false,
  },
  {
    key: 'Grapple',
    label: 'PF2E.Actions.Grapple.Title',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'remove-fear',
    featRequired: false,
  },
  {
    key: 'Trip',
    label: 'PF2E.Actions.Trip.Title',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'natures-enmity',
    featRequired: false,
  },
  {
    key: 'Demoralize',
    label: 'PF2E.Actions.Demoralize.Title',
    proficiencyKey: 'itm',
    trainingRequired: false,
    icon: 'blind-ambition',
    featRequired: false,
  },
  {
    key: 'Shove',
    label: 'PF2E.Actions.Shove.Title',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'ki-strike',
    featRequired: false,
  },
  {
    key: 'Feint',
    label: 'PF2E.Actions.Feint.Title',
    proficiencyKey: 'dec',
    trainingRequired: true,
    icon: 'delay-consequence',
    featRequired: false,
  },
  {
    key: 'Bon Mot',
    label: 'PF2E.Actions.BonMot.Title',
    proficiencyKey: 'dip',
    trainingRequired: false,
    icon: 'hideous-laughter',
    featRequired: true,
    featSlug: 'bon-mot',
  },
];
