export const SKILL_ACTIONS_DATA = [
  {
    key: 'disarm',
    label: 'Disarm',
    proficiencyKey: 'ath',
    trainingRequired: true,
    icon: 'perfect-strike',
    featRequired: false,
  },
  {
    key: 'grapple',
    label: 'Grapple',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'remove-fear',
    featRequired: false,
  },
  {
    key: 'trip',
    label: 'Trip',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'natures-enmity',
    featRequired: false,
  },
  {
    key: 'demoralize',
    label: 'Demoralize',
    proficiencyKey: 'itm',
    trainingRequired: false,
    icon: 'blind-ambition',
    featRequired: false,
  },
  {
    key: 'shove',
    label: 'Shove',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'ki-strike',
    featRequired: false,
  },
  {
    key: 'feint',
    label: 'Feint',
    proficiencyKey: 'dec',
    trainingRequired: true,
    icon: 'delay-consequence',
    featRequired: false,
  },
  {
    key: 'bonMot',
    label: 'Bon Mot',
    proficiencyKey: 'dip',
    trainingRequired: false,
    icon: 'hideous-laughter',
    featRequired: true,
  },
];
