export const SKILL_ACTIONS_DATA = [
  {
    key: 'disarm',
    label: 'PF2E.Actions.Disarm.Title',
    proficiencyKey: 'ath',
    trainingRequired: true,
    icon: 'perfect-strike',
    featRequired: false,
  },
  {
    key: 'grapple',
    label: 'PF2E.Actions.Grapple.Title',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'remove-fear',
    featRequired: false,
  },
  {
    key: 'trip',
    label: 'PF2E.Actions.Trip.Title',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'natures-enmity',
    featRequired: false,
  },
  {
    key: 'demoralize',
    label: 'PF2E.Actions.Demoralize.Title',
    proficiencyKey: 'itm',
    trainingRequired: false,
    icon: 'blind-ambition',
    featRequired: false,
  },
  {
    key: 'shove',
    label: 'PF2E.Actions.Shove.Title',
    proficiencyKey: 'ath',
    trainingRequired: false,
    icon: 'ki-strike',
    featRequired: false,
  },
  {
    key: 'feint',
    label: 'PF2E.Actions.Feint.Title',
    proficiencyKey: 'dec',
    trainingRequired: true,
    icon: 'delay-consequence',
    featRequired: false,
  },
  {
    key: 'bon-mot',
    label: 'PF2E.Actions.BonMot.Title',
    proficiencyKey: 'dip',
    trainingRequired: false,
    icon: 'hideous-laughter',
    featRequired: true,
  },
];
